#
# Ensure we do not use any libraries that have licenses incompatible ASL-2 / MIT
#

[licenses]
unlicensed = "deny"
default = "deny"
copyleft = "deny"
allow = [
  # "0BSD",
  "Apache-2.0",
  # "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  # "CC0-1.0",
  # "ISC",
  "MIT",
  # "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib"
]

exceptions = [
    # MPL-2.0 are added case-by-case to make sure we are in compliance. To be in
    # compliance we cannot be modifying the source files.
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [ ]
