[package]
name = "noenv"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1"
tracing = "0.1"
tracing-axiom = { path = "../../" }
axiom-rs = "0.3"
uuid = { version = "1", features = ["v4"] }
